version: '2'

services:
  # Before building any of these containers; please run
  # docker-compose -f docker-compose.build.yml build
  # as that will build the base images
 
  # HDFS Starts here...
  namenode:
    image: karlstoney/namenode
    build: ./namenode 
    restart: always
    hostname: namenode
    container_name: namenode
    ports:
      - 17000:50070
    mem_limit: 512m
    memswap_limit: 2g
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./stack.env

  datanode:
    image: karlstoney/datanode 
    build: ./datanode
    restart: always
    hostname: datanode
    container_name: datanode
    mem_limit: 512m
    memswap_limit: 2g
    env_file:
      - ./stack.env

  resourcemanager:
    image: karlstoney/resourcemanager 
    build: ./resourcemanager
    restart: always
    hostname: resourcemanager
    container_name: resourcemanager
    mem_limit: 512m
    memswap_limit: 2g
    env_file:
      - ./stack.env
