version: '2'

networks:
  hbase:

services:
  hbase:
    hostname: hbase
    domainname: hadoop
    build: ./hbase
    restart: always
    networks:
      hbase:
    environment:
      - HBASE_MANAGES_ZK=true
      - QUORUM=hbase
    depends_on:
      - namenode
      - datanode1
      - datanode2
    ports:
      - 8080:8080   # Rest
      - 9090:9090   # Thrift API
      - 9095:9095   # Thrift UI
      - 2181:2181   # Zookeeper 
      - 16000:16000 # Master API
      - 16010:16010 # Master UI
      - 16020:16020 # Region API
      - 16030:16030 # Region UI

  hue:
    image: gethue/hue:latest 
    hostname: hue
    container_name: hue
    domainname: hadoop
    depends_on:
      - hbase
    networks:
      - hbase
    ports:
      - 8088:8088
       
  namenode:
    image: bde2020/hadoop-namenode:1.0.0
    hostname: namenode
    container_name: namenode
    domainname: hadoop
    networks:
      - hbase
    environment:
      - CLUSTER_NAME=test
    depends_on:
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
      - 8020:8020

  datanode1:
    image: bde2020/hadoop-datanode:1.0.0
    hostname: datanode1
    container_name: datanode1
    domainname: hadoop
    networks:
      - hbase
    env_file:
      - ./hadoop.env

  datanode2:
    image: bde2020/hadoop-datanode:1.0.0
    hostname: datanode2
    container_name: datanode2
    domainname: hadoop
    networks: 
      - hbase
    env_file:
      - ./hadoop.env

