version: '2'

services:
  # HDFS
  namenode:
    extends:
      file: compose.hdfs.yml
      service: namenode

  datanode1:
    extends:
      file: compose.hdfs.yml
      service: datanode
    container_name: datanode1
    hostname: datanode1
    depends_on:
      - namenode

  datanode2:
    extends:
      file: compose.hdfs.yml
      service: datanode
    container_name: datanode2
    hostname: datanode2
    depends_on:
      - namenode

  resourcemanager:
    extends:
      file: compose.hdfs.yml
      service: resourcemanager
    container_name: resourcemanager
    hostname: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2

  # HBase
  zookeeper:
    extends:
      file: compose.hbase.yml
      service: zookeeper

  regionserver:
    extends:
      file: compose.hbase.yml
      service: regionserver
    depends_on:
      - datanode1
      - datanode2

  master:
    extends: 
      file: compose.hbase.yml
      service: master
    depends_on:
      - zookeeper
      - regionserver

  thrift:
    extends: 
      file: compose.hbase.yml
      service: thrift
    depends_on:
      - master

  rest:
    extends: 
      file: compose.hbase.yml
      service: rest
    depends_on:
      - master

  # The ELK stack, lul
  solr:
    extends: 
      file: compose.other.yml
      service: solr
    depends_on:
      - zookeeper
      - master

  banana:
    extends: 
      file: compose.other.yml
      service: banana
    depends_on:
      - solr

  lily:
    extends: 
      file: compose.other.yml
      service: lily
    depends_on:
      - zookeeper
      - master
      - solr

  # Other tools 
  nifi:
    extends: 
      file: compose.other.yml
      service: nifi
    depends_on:
      - master

  hue:
    extends: 
      file: compose.other.yml
      service: hue
    depends_on:
      - master
      - thrift
      - rest
      - solr
      - zookeeper

  zkweb:
    extends: 
      file: compose.other.yml
      service: zkweb
    depends_on:
      - zookeeper
